### ISSUE TITLE
Docs: Updating Readme.md

### ISSUE THREAD

**Issue by trinetra110** [dscnsec/Pomodoro-Timer#1]
## Description

Giving proper structure to Readme.md and adding banner for hacktoberfest, badges, emoji's, etc. to get a clear understanding of the project and to attract Contributors to contribute in this project.

## Additional note

Please add "hacktoberfest" label to this issue.

**Comment by shivisingh25** [comment]
@trinetra110 Sure go ahead! Assigning to you
