### ISSUE TITLE
UI: Add Header

### ISSUE THREAD

**Issue by shivisingh25** [dscnsec/Pomodoro-Timer#3]
## Description
Add header with title `POMODORO` in the Home Page. Alignment should be `Centre`.

## Task
- Use [Google inter fonts](https://fonts.google.com/specimen/Inter) for Header

## Demo
![image](https://github.com/user-attachments/assets/380fd796-7a86-4bc6-b1f8-a8e5fcf60477)

**Comment by EmanuelCG** [comment]
Hi, you can do it by applying these styles:

```
        body {
            margin: 0;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: 'Inter', sans-serif;
        }

        h1 {
            font-size: 3em;
            font-weight: 700;
            text-align: center;
        }
```

**Comment by NikitaKarmakarP** [comment]
@shivisingh25 Please assign me this issue

**Comment by shivisingh25** [comment]
@NikitaKarmakarP You can proceed now.
